name: Periodic HealthCheck Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 everyday
jobs:
  check_url:
    steps:
      - name: Check the deployed URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://runic.onrender.com|https://runic.onrender.com
          follow-redirect: false
          max-attempts: 6
          retry-delay: 20s
          retry-all: false
