name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies Backend
        run: npm install
      - name: Install Dependencies Frontend
        run: cd frontend/ && npm install
      - name: Format
        run: npm run prettier
      - name: Lint
        run: npm run eslint
      - name: Build Backend
        run: npm run build:be
      - name: Build Frontend
        run: yarn run build:fe
      - name: Backend Tests
        run: npm run test
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

      - name: e2e Test
        uses: cypress-io/github-action@v4
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
        with:
          start: npm run start:test
          wait-on: http://localhost:8000

      - name: Build Project Artifacts on Production
        if: ${{ success() }}
        run: npm run build

  release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: PIMPfiction/AutoTagVersionRelease@v1
        with:
          github-token: ${{ secrets.PAT }}
