name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies Backend
        run: yarn
      - name: Install Dependencies Frontend
        run: cd frontend/ && yarn
      - name: Format
        run: npm run prettier
      - name: Lint
        run: npm run eslint
      - name: Build Backend
        run: yarn build:be
      - name: Build Frontend
        run: yarn build:fe
      - name: Backend Tests
        run: yarn test
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

      - name: e2e Test
        uses: cypress-io/github-action@v4
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
        with:
          start: yarn start:test
          wait-on: http://localhost:8000

  deploy:
    if: ${{ (github.event.pull_request.merged == true) && (!contains(github.event.head_commit.message, '#skip')) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Backend Dependencies
        run: yarn
      - name: Install Frontend Dependencies
        run: cd frontend/ && yarn
      - name: Create Root ENV File
        run: |
          touch .env
          echo REACT_APP_BASE_URL="https://runic.onrender.com" >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env
      - name: Build Project Artifacts for Backend
        run: yarn build:be
      - name: Create Frontend ENV File
        run: |
          cd frontend/ && rm -rf .env.development && touch .env
          echo REACT_APP_BASE_URL="https://runic-tau.vercel.app" >> .env
          cat .env
      - name: Build Frontend Project Artifacts
        run: yarn build:fe
      - name: Deploy Project Artifacts to RENDER
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  release:
    runs-on: ubuntu-latest
    needs: [deploy]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: PIMPfiction/AutoTagVersionRelease@v1
        with:
          github-token: ${{ secrets.PAT }}
