name: Pull Request Pipeline

on:
  # push:
  # branches: ['main']
  # paths-ignore:
  # - 'README.md'
  pull_request_review:
    types: [submitted]

# env:
# VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
# VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies Backend
        run: yarn install --immutable
      - name: Install Dependencies Frontend
        run: cd frontend/ && yarn install --immutable
      - name: Format
        run: yarn run prettier
      - name: Lint
        run: yarn run eslint
      - name: Build Backend
        run: yarn run build:be
      - name: Build Frontend
        run: yarn run build:fe
      - name: Backend Tests
        run: yarn run test
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

      - name: e2e Test
        uses: cypress-io/github-action@v4
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
        with:
          # build: yarn run build
          start: yarn run start:test
          wait-on: http://localhost:8000

  release:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "This PR was approved"
   